version: 2.1

orbs:
  android: wordpress-mobile/android@0.0.22

commands:
  copy-gradle-properties:
    steps:
      - run:
          name: Setup gradle.properties
          command: cp gradle.properties-example gradle.properties

jobs:
  Lint:
    executor:
      name: android/default
      api-version: "27"
    steps:
      - checkout
      - copy-gradle-properties
      - android/restore-gradle-cache
      - run:
          name: Lint & Checkstyle
          command: ./gradlew --stacktrace lint checkstyle
      - android/save-gradle-cache
      - android/save-lint-results
  Test:
    executor:
      name: android/default
      api-version: "27"
    steps:
      - checkout
      - copy-gradle-properties
      - android/restore-gradle-cache
      - run:
          name: Test
          command: ./gradlew --stacktrace test
      - android/save-gradle-cache
  Build and upload to Bintray:
    executor:
      name: android/default
      api-version: "27"
    steps:
      - checkout
      - copy-gradle-properties
      - android/restore-gradle-cache
      - run:
          name: Experimental Bintray Upload
          command: |
            branch=$CIRCLE_BRANCH
            if [[ -n "$CIRCLE_PULL_REQUEST" ]]; then
              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
              # Making the assumption that $CIRCLE_SHA1 will always be
              # available. Also, cutting the full SHA into the first 7
              # characters only because otherwise the upload of the .pom fails.
              # Not sure why that would be the case, but it is.
              PREFIX="$PR_NUMBER-${CIRCLE_SHA1:0:7}"
            elif [[ "$branch" != "trunk" && "$branch" != "develop" && "$branch" != "master" ]]; then
              # Checked on master as well for retro-compatibility.
              # Once all of the projects have migrated to trunk, we shall remove
              # that check.
              echo "Running on a feature branch with no open PR: skipping Bintray upload"
              exit 0
            else
              echo "Running on a production branch: skipping while trying to figure out a clean way to avoid republishing the same version."
              exit 0
            fi

            # Locally, calling `./gradlew bintrayUpload` is enough to generate
            # all the required artifacts. On CI, unless run each task
            # individually, the Bintray task will fail to find the .aar and
            # pom.xml artifacts in the build/ folder.
            ./gradlew --stacktrace assembleRelease
            # On local, the POM is generated automatically as part of
            # assembleRelease, but that doesn't seem to be the case on CI. Here
            # we need to explicitly generated it, otherwise bintrayUpload won't
            # find it and won't upload it.
            #
            # Worth noting that the Bintray plugin mentions the necessity for
            # a workaround to generate the POM. See:
            # https://github.com/bintray/gradle-bintray-plugin#maven-publications
            #
            # See also the description and comments in this PR:
            # https://github.com/wordpress-mobile/WordPress-Utils-Android/pull/39
            #
            # Notice the `-PbintrayVersion` parameter to make sure the POM has
            # the same version as the one bintrayUpload will use.
            ./gradlew --stacktrace generatePomFileForUtilsPublicationPublication -PbintrayVersion=$PREFIX

            # If $PREFIX is not set, that is, if we're not on a PR but a merge
            # commit on develop or trunk, the plugin will fallback to reading
            # the version value from the source code.
            ./gradlew --stacktrace bintrayUpload -PbintrayVersion=$PREFIX
      - android/save-gradle-cache

workflows:
  # We don't want this to run on tags, but no filter statement is necessary
  # because that's the default behavior
  WordPress-Utils-Android:
    jobs:
      # - Lint
      # - Test
      # - Build:
      #     requires:
      #       - Test
      # - Build and upload to Bintray:
      #     requires:
      #       - Build
      - Build and upload to Bintray
