version: 2.1

orbs:
  android: wordpress-mobile/android@1.0.21

commands:
  copy-gradle-properties:
    steps:
      - run:
          name: Setup gradle.properties
          command: cp gradle.properties-example gradle.properties

jobs:
  Lint:
    executor:
      name: android/default
      api-version: "27"
    steps:
      - checkout
      - copy-gradle-properties
      - android/restore-gradle-cache
      - run:
          name: Lint & Checkstyle
          command: ./gradlew --stacktrace lint checkstyle
      - android/save-gradle-cache
      - android/save-lint-results
  Test:
    executor:
      name: android/default
      api-version: "27"
    steps:
      - checkout
      - copy-gradle-properties
      - android/restore-gradle-cache
      - run:
          name: Test
          command: ./gradlew --stacktrace test
      - android/save-gradle-cache
  Build and upload to S3:
    executor:
      name: android/default
      api-version: "27"
    steps:
      - android/check-precondition-for-publish-artifacts
      - checkout
      - copy-gradle-properties
      - android/restore-gradle-cache
      - android/publish-to-s3:
          publish_gradle_task: :WordPressUtils:publishLibraryToS3
      - android/save-gradle-cache

workflows:
  WordPress-Utils-Android:
    jobs:
      - Lint
      - Test:
          filters:
            tags:
              only: /.*/
      - Build and upload to S3:
          requires:
            - Test 
          filters:
            tags:
              only: /.*/

